services:
  data_db:
    image: postgres:14.7
    container_name: "db.dnd.skelmis.co.nz"
    restart: always
    command: -p 2401
    ports:
      - "2401:2401"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: dnd_skelmis_co_nz
      POSTGRES_USER: data_autohelp_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  data_web:
    image: ghcr.io/skelmis/dnd-money-tracker:master
    container_name: "web_dnd.skelmis.co.nz"
    restart: always
    ports:
      - "2400:2400"
    depends_on:
      - data_db
    cpus: 1
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      SERVING_DOMAIN: "dnd.skelmis.co.nz"
      POSTGRES_HOST: db.dnd.skelmis.co.nz
      POSTGRES_DB: its_a_db_woo
      POSTGRES_USER: its_a_db_woo_user
      POSTGRES_PASSWORD: its_a_db_woo_password_for_db_user
      POSTGRES_PORT: 2401

#networks:
#  default:
#    name: spook
#    external: true